name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack via Cargo
        run: cargo install wasm-pack

      - name: Build wasm package
        run: |
          cd language
          wasm-pack build

      - name: Build and Deploy Web Frontend
        run: |
          cd blockpipe-web-frontend
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: blockpipe-web-frontend/dist
